_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 50

accelerator: cpu
devices: 1

# mixed precision for extra speed-up
precision: 16-mixed

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1
# check in one epoch
# val_check_interval: 0.05

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

# 这是开始训练前的进行eval的个数，一定要保证datamodule可以运行
num_sanity_val_steps: 2