_target_: src.models.lbl_module.LBLLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-5

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
  # _target_: monai.optimizers.WarmupCosineSchedule
  # _partial_: true
  # warmup_steps: 10
  # t_total: 200

net:
  _target_: src.models.components.resnet.ResNet50
  block: "bottleneck"
  layers: [3, 4, 6, 3]
  block_inplanes: [64, 128, 256, 512]
  spatial_dims: 3
  n_input_channels: 1
  num_classes: 2

# compile model for faster training with pytorch 2.0
compile: false
