defaults:
  - _self_
  - optimizer

_target_: src.models.lbl_module.LBLLitModule

net:
  _target_: src.models.components.vit.ViT
  img_size: [256, 256, 32]
  patch_size: [16, 16, 16]
  spatial_dims: 3
  in_channels: 1
  num_classes: 2
  classification: True
  dropout_rate: 0
  post_activation: None
