defaults:
  - _self_
  - optimizer

_target_: src.models.lbl_module.LBLLitModule

net:
  _target_: src.models.components.resnet.ResNet50
  block: "bottleneck"
  layers: [3, 4, 6, 3]
  block_inplanes: [64, 128, 256, 512]
  spatial_dims: 3
  n_input_channels: 1
  num_classes: 2
