defaults:
  - _self_
  - optimizer

model_name: ConvNeXt

_target_: src.models.lbl_module.LBLLitModule

net:
  _target_: src.models.components.convnext.ConvNeXt
  in_chans: 3
  num_classes: 2
  # depths: [3, 3, 9, 3]
  # dims: [96, 192, 384, 768]
  # use_grn: True
  # conv_mlp: False
