defaults:
  - _self_
  - optimizer

model_name: ResNet

_target_: src.models.lbl_module.LBLLitModule

# net:
#   _target_: src.models.components.resnet.ResNet
#   block: "basic"
#   # resnet34
#   layers: [3, 4, 6, 3]
#   # resnet18
#   # layers: [2, 2, 2, 2]
#   block_inplanes: [64, 128, 256, 512]
#   shortcut_type: A
#   bias_downsample: True
#   spatial_dims: 3
#   n_input_channels: 1
#   num_classes: 2

# resnet50
net:
  _target_: src.models.components.resnet.ResNet
  block: "bottleneck"
  layers: [3, 4, 6, 3]
  block_inplanes: [64, 128, 256, 512]
  shortcut_type: B
  bias_downsample: False
  spatial_dims: 2
  n_input_channels: 3
  num_classes: 2
# # resnet10
# net:
#   _target_: src.models.components.resnet.ResNet
#   block: "basic"
#   layers: [1, 1, 1, 1]
#   block_inplanes: [64, 128, 256, 512]
#   shortcut_type: B
#   bias_downsample: False
#   spatial_dims: 3
#   n_input_channels: 1
#   num_classes: 2

# # resnet18
# net:
#   _target_: src.models.components.resnet.ResNet
#   block: "basic"
#   layers: [2, 2, 2, 2]
#   block_inplanes: [64, 128, 256, 512]
#   shortcut_type: A
#   bias_downsample: True
#   spatial_dims: 2
#   n_input_channels: 3
#   num_classes: 2
