defaults:
  - _self_
  - optimizer

model_name: ViT

_target_: src.models.lbl_module.LBLLitModule

net:
  _target_: src.models.components.vit.ViT
  in_channels: 3
  num_classes: 2
  # img_size: ${data.input_size}
  # patch_size: [16, 16]
  # spatial_dims: 2
  # classification: True
  # dropout_rate: 0
  # post_activation: None
