defaults:
  - _self_
  - optimizer

model_name: MedMamba

_target_: src.models.lbl_module.LBLLitModule

net:
  _target_: src.models.components.medmamba.VSSM
  in_chans: 3
  num_classes: 2
  depths: [2, 2, 4, 2]
  dims: [96,192,384,768]
