defaults:
  - _self_
  - optimizer

model_name: SwinT

_target_: src.models.lbl_module.LBLLitModule

net:
  _target_: src.models.components.swint.SwinTransformer
  in_chans: 3
  num_classes: 2
  # embed_dim: 192
  # window_size: 16
  # patch_size: 16
  # depths: [2, 2, 6, 2]
  # num_heads: [3, 6, 12, 24]
  # spatial_dims: 2
  # classification: True