_target_: src.models.lbl_module.LBLLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-5

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
  # _target_: monai.optimizers.WarmupCosineSchedule
  # _partial_: true
  # warmup_steps: 10
  # t_total: 200

net:
  _target_: src.models.components.vit.ViT
  img_size: [256, 256, 32]
  patch_size: [16, 16, 16]
  spatial_dims: 3
  in_channels: 1
  num_classes: 2
  classification: True
  dropout_rate: 0
  post_activation: None

# compile model for faster training with pytorch 2.0
compile: false
