# @package _global_

defaults:
  - _self_
  - data: lbl
  - model: lbl_resnet
  - callbacks: default
  - logger: csv
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ['resnet']

# # mamba
# ckpt_path: ${paths.root_dir}/logs/train/multiruns/2024-11-07_20-14-41/0/checkpoints/epoch_032.ckpt
# resnet
ckpt_path: ${paths.root_dir}/logs/train/multiruns/2024-11-07_20-14-43/0/checkpoints/epoch_043.ckpt
# vit
# ckpt_path: logs/train/multiruns/2024-11-05_23-57-23/0/checkpoints/epoch_019.ckpt
# seed: ${data.seed}
