# @package _global_

defaults:
  - _self_
  - data: lbl
  - model: lbl_vit
  - callbacks: default
  - logger: csv
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ['vit']

# # mamba
# ckpt_path: ${paths.root_dir}/logs/train/multiruns/2024-11-05_23-55-43/0/checkpoints/epoch_049.ckpt
# # resnet
# ckpt_path: logs/train/multiruns/2024-11-05_23-57-01/0/checkpoints/epoch_024.ckpt
# vit
ckpt_path: logs/train/multiruns/2024-11-05_23-57-23/0/checkpoints/epoch_019.ckpt
seed: ${data.seed}
