# @package _global_

defaults:
  - _self_
  - data: lbl
  - model: lbl_mamba
  - callbacks: default
  - logger: csv
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ['mamba']

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.root_dir}/logs/train/runs/2024-11-05_18-09-55/checkpoints/epoch_064.ckpt

seed: ${data.seed}
