# @package _global_

defaults:
  - _self_
  - data: lbl
  - model: lbl_resnet
  - callbacks: default
  - logger: csv
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.root_dir}/logs/train/runs/2024-10-28_16-24-06/checkpoints/last.ckpt
